version: '3.7'
services: 


  app:
    image: cabal-bn-api
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DEV_DATABASE_URL=${DEV_DATABASE_URL}
      - BASE_URL=${BASE_URL}
    build:
      context: .
      args:
        - PORT:${PORT}
    volumes:
      - ./:/usr/src/app/
    container_name: cabal-backend
    
    depends_on:
      - db

    ports: 
      - "5000:5000"
    
    links:
      - redis: redis
    
    restart: always
    
  db:

    image: postgres:14.1-alpine
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: cabal_db
  
  redis: 

    image: redis
    restart: always
    command: redis-server
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      
    container_name: cabal_redis