version: 2.1

orbs:
coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0

    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: run test
          command: yarn run test
      - run:
        name: coverage
        command: yarn run coverage

      - coveralls/upload
      - store_artifacts:
          path: test-results
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results
      - run: # test what branch we're on.
          name: 'What branch am I on?'
          command: echo ${CIRCLE_BRANCH}
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
workflows:
  test-deploy:
    jobs:
      - build
