# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# trigger build when pushing, or when creating a pull request
on: [push, pull_request]

jobs:
  build:
    # run build on latest ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run build for both Node version 12 and version 14
        node-version: [12.x, 14.x, 16.x]

    steps:
      # for checking out the branch (https://github.com/actions/checkout#Push-a-commit-using-the-built-in-token)
      - uses: actions/checkout@v2
      # installing Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          # this is regarding the matrix strategy specified above
          node-version: ${{ matrix.node-version }}
      # install dependencies
      - run: yarn ci
      # build the project if necessary
      - run: yarn run build --if-present
      - run: yarn run coverage

      # Send coverage report to Coveralls
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
